# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - baxter_right_arm_controller
    - baxter_left_arm_controller
    - baxter_right_hand_controller
    - baxter_left_hand_controller


  baxter_right_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2

  baxter_left_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2

  baxter_right_hand_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - r_gripper_l_finger_joint

  baxter_left_hand_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - l_gripper_l_finger_joint
  