# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    baxter_right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    baxter_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    baxter_right_hand_controller:
      type: position_controllers/GripperActionController

    baxter_left_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


baxter_right_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2

baxter_left_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2

baxter_right_hand_controller:
  ros__parameters:
    joint: r_gripper_l_finger_joint

baxter_left_hand_controller:
  ros__parameters:
    joint: l_gripper_l_finger_joint
